apiVersion: v1
kind: Service
metadata:
  name: catalog-database
spec:
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  selector:
    name: catalog-database
  sessionAffinity: None
  type: ClusterIP

